### ISSUE TITLE
Multiple sites dynamically

### ISSUE THREAD

**Issue by oskarvisual** [spotman/kohana-multi-site#2]
I can dynamically add more sites? is that possible? eg when adding a new company that will add to that company automatically a new site (eg domain.com/empresa2)

**Comment by spotman** [comment]
Hi, oskarvisual!

It is possible but not via this module directly. There are two ways to do this:

- dynamically create new site directory + new apache/nginx site config + reload apache/nginx, or
- implement routing strategies and rewrite the core class to use one of them (selectable via module config).

If you'll choose the second way, I may help you with refactoring and implementing new routing logic.
The current version was developed to be fast so the new one must not have any performance leaks too.

Thanks!

**Comment by spotman** [comment]
@oskarvisual is this issue still actial for you?

**Comment by spotman** [comment]
Closed coz no response.
